//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace UpdateControls.Correspondence.POXClient.Contract {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=false)]
    public partial class GetRequest {
        
        private FactTree pivotTreeField;
        
        private long pivotIdField;
        
        private bool pivotIdFieldSpecified;
        
        private long timestampField;
        
        private bool timestampFieldSpecified;
        
        private string clientGuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FactTree PivotTree {
            get {
                return this.pivotTreeField;
            }
            set {
                this.pivotTreeField = value;
            }
        }
        
        /// <remarks/>
        public long PivotId {
            get {
                return this.pivotIdField;
            }
            set {
                this.pivotIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PivotIdSpecified {
            get {
                return this.pivotIdFieldSpecified;
            }
            set {
                this.pivotIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ClientGuid {
            get {
                return this.clientGuidField;
            }
            set {
                this.clientGuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=true)]
    public partial class FactTree {
        
        private long databaseIdField;
        
        private bool databaseIdFieldSpecified;
        
        private Fact[] factsField;
        
        private FactRole[] rolesField;
        
        private long timestampField;
        
        private bool timestampFieldSpecified;
        
        private FactType[] typesField;
        
        /// <remarks/>
        public long DatabaseId {
            get {
                return this.databaseIdField;
            }
            set {
                this.databaseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatabaseIdSpecified {
            get {
                return this.databaseIdFieldSpecified;
            }
            set {
                this.databaseIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Fact[] Facts {
            get {
                return this.factsField;
            }
            set {
                this.factsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public FactRole[] Roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
        
        /// <remarks/>
        public long Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public FactType[] Types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=true)]
    public partial class Fact {
        
        private byte[] dataField;
        
        private long factIdField;
        
        private bool factIdFieldSpecified;
        
        private int factTypeIdField;
        
        private bool factTypeIdFieldSpecified;
        
        private Predecessor[] predecessorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public long FactId {
            get {
                return this.factIdField;
            }
            set {
                this.factIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FactIdSpecified {
            get {
                return this.factIdFieldSpecified;
            }
            set {
                this.factIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int FactTypeId {
            get {
                return this.factTypeIdField;
            }
            set {
                this.factTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FactTypeIdSpecified {
            get {
                return this.factTypeIdFieldSpecified;
            }
            set {
                this.factTypeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Predecessor[] Predecessors {
            get {
                return this.predecessorsField;
            }
            set {
                this.predecessorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=true)]
    public partial class Predecessor {
        
        private long predecessorIdField;
        
        private bool predecessorIdFieldSpecified;
        
        private int roleIdField;
        
        private bool roleIdFieldSpecified;
        
        /// <remarks/>
        public long PredecessorId {
            get {
                return this.predecessorIdField;
            }
            set {
                this.predecessorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PredecessorIdSpecified {
            get {
                return this.predecessorIdFieldSpecified;
            }
            set {
                this.predecessorIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoleIdSpecified {
            get {
                return this.roleIdFieldSpecified;
            }
            set {
                this.roleIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=true)]
    public partial class FactRole {
        
        private int declaringTypeIdField;
        
        private bool declaringTypeIdFieldSpecified;
        
        private bool isPivotField;
        
        private bool isPivotFieldSpecified;
        
        private int roleIdField;
        
        private bool roleIdFieldSpecified;
        
        private string roleNameField;
        
        private int targetTypeIdField;
        
        private bool targetTypeIdFieldSpecified;
        
        /// <remarks/>
        public int DeclaringTypeId {
            get {
                return this.declaringTypeIdField;
            }
            set {
                this.declaringTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeclaringTypeIdSpecified {
            get {
                return this.declaringTypeIdFieldSpecified;
            }
            set {
                this.declaringTypeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsPivot {
            get {
                return this.isPivotField;
            }
            set {
                this.isPivotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPivotSpecified {
            get {
                return this.isPivotFieldSpecified;
            }
            set {
                this.isPivotFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoleIdSpecified {
            get {
                return this.roleIdFieldSpecified;
            }
            set {
                this.roleIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
        
        /// <remarks/>
        public int TargetTypeId {
            get {
                return this.targetTypeIdField;
            }
            set {
                this.targetTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TargetTypeIdSpecified {
            get {
                return this.targetTypeIdFieldSpecified;
            }
            set {
                this.targetTypeIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=true)]
    public partial class FactType {
        
        private int typeIdField;
        
        private bool typeIdFieldSpecified;
        
        private string typeNameField;
        
        private int versionField;
        
        private bool versionFieldSpecified;
        
        /// <remarks/>
        public int TypeId {
            get {
                return this.typeIdField;
            }
            set {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeIdSpecified {
            get {
                return this.typeIdFieldSpecified;
            }
            set {
                this.typeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=true)]
    public partial class ArrayOfFact {
        
        private Fact[] factField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fact", IsNullable=true)]
        public Fact[] Fact {
            get {
                return this.factField;
            }
            set {
                this.factField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=true)]
    public partial class ArrayOfPredecessor {
        
        private Predecessor[] predecessorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Predecessor", IsNullable=true)]
        public Predecessor[] Predecessor {
            get {
                return this.predecessorField;
            }
            set {
                this.predecessorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=true)]
    public partial class ArrayOfFactRole {
        
        private FactRole[] factRoleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FactRole", IsNullable=true)]
        public FactRole[] FactRole {
            get {
                return this.factRoleField;
            }
            set {
                this.factRoleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=true)]
    public partial class ArrayOfFactType {
        
        private FactType[] factTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FactType", IsNullable=true)]
        public FactType[] FactType {
            get {
                return this.factTypeField;
            }
            set {
                this.factTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=false)]
    public partial class GetResponse {
        
        private FactTree getResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FactTree GetResult {
            get {
                return this.getResultField;
            }
            set {
                this.getResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=false)]
    public partial class PostRequest {
        
        private FactTree messageBodyField;
        
        private string clientGuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FactTree MessageBody {
            get {
                return this.messageBodyField;
            }
            set {
                this.messageBodyField = value;
            }
        }
        
        /// <remarks/>
        public string ClientGuid {
            get {
                return this.clientGuidField;
            }
            set {
                this.clientGuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://correspondence.updatecontrols.com/pox/1.0", IsNullable=false)]
    public partial class PostResponse {
    }
}
