..\.nuget\nuget pack Core\Correspondence.nuspec
..\.nuget\nuget pack Model\Correspondence.Model.nuspec
..\.nuget\nuget pack UnitTest\Correspondence.UnitTest.nuspec
..\.nuget\nuget pack UnitTest.Core\Correspondence.UnitTest.Core.nuspec
..\.nuget\nuget pack App\Correspondence.App.nuspec
..\.nuget\nuget pack App.Core\Correspondence.App.Core.nuspec
..\.nuget\nuget pack AllInOne\Correspondence.AllInOne.nuspec
..\.nuget\nuget pack Web.App\Correspondence.Web.App.nuspec
..\.nuget\nuget pack Web.App.Core\Correspondence.Web.App.Core.nuspec
..\.nuget\nuget pack Web.AllInOne\Correspondence.Web.AllInOne.nuspec
