nuget pack Core\Correspondence.nuspec
nuget pack Model\Correspondence.Model.nuspec
nuget pack UnitTest\Correspondence.UnitTest.nuspec
nuget pack WindowsPhone\App\Correspondence.WindowsPhone.App.nuspec
nuget pack WindowsPhone\AllInOne\Correspondence.WindowsPhone.AllInOne.nuspec
nuget pack Silverlight\App\Correspondence.Silverlight.App.nuspec
nuget pack Silverlight\AllInOne\Correspondence.Silverlight.AllInOne.nuspec
nuget pack Desktop\App\Correspondence.Desktop.App.nuspec
nuget pack Desktop\AllInOne\Correspondence.Desktop.AllInOne.nuspec
nuget pack Web\App\Correspondence.Web.App.nuspec
nuget pack Web\AllInOne\Correspondence.Web.AllInOne.nuspec
nuget pack WinRT\App\Correspondence.WinRT.App.nuspec
nuget pack WinRT\AllInOne\Correspondence.WinRT.AllInOne.nuspec
