nuget pack Core\Correspondence.nuspec
nuget pack Model\Correspondence.Model.nuspec
nuget pack WindowsPhone\UnitTest\Correspondence.WindowsPhone.UnitTest.nuspec
nuget pack WindowsPhone\App\Correspondence.WindowsPhone.App.nuspec
nuget pack WindowsPhone\AllInOne\Correspondence.WindowsPhone.AllInOne.nuspec
nuget pack Silverlight\UnitTest\Correspondence.Silverlight.UnitTest.nuspec
nuget pack Silverlight\App\Correspondence.Silverlight.App.nuspec
nuget pack Silverlight\AllInOne\Correspondence.Silverlight.AllInOne.nuspec
nuget pack Desktop\UnitTest\Correspondence.Desktop.UnitTest.nuspec
nuget pack Desktop\App\Correspondence.Desktop.App.nuspec
nuget pack Desktop\AllInOne\Correspondence.Desktop.AllInOne.nuspec
nuget pack Web\UnitTest\Correspondence.Web.UnitTest.nuspec
nuget pack Web\App\Correspondence.Web.App.nuspec
nuget pack Web\AllInOne\Correspondence.Web.AllInOne.nuspec
