//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace UpdateControls.Correspondence.POXClient.Contract
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = true)]
    public partial class FactTree
    {

        private long databaseIdField;

        private Fact[] factsField;

        private FactRole[] rolesField;

        private FactType[] typesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DatabaseId
        {
            get
            {
                return this.databaseIdField;
            }
            set
            {
                this.databaseIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Fact[] Facts
        {
            get
            {
                return this.factsField;
            }
            set
            {
                this.factsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FactRole[] Roles
        {
            get
            {
                return this.rolesField;
            }
            set
            {
                this.rolesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FactType[] Types
        {
            get
            {
                return this.typesField;
            }
            set
            {
                this.typesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = true)]
    public partial class Fact
    {

        private byte[] dataField;

        private long factIdField;

        private int factTypeIdField;

        private Predecessor[] predecessorsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", IsNullable = true)]
        public byte[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long FactId
        {
            get
            {
                return this.factIdField;
            }
            set
            {
                this.factIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int FactTypeId
        {
            get
            {
                return this.factTypeIdField;
            }
            set
            {
                this.factTypeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Predecessor[] Predecessors
        {
            get
            {
                return this.predecessorsField;
            }
            set
            {
                this.predecessorsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = true)]
    public partial class Predecessor
    {

        private long predecessorIdField;

        private int roleIdField;

        private System.Nullable<bool> isPivotField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PredecessorId
        {
            get
            {
                return this.predecessorIdField;
            }
            set
            {
                this.predecessorIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RoleId
        {
            get
            {
                return this.roleIdField;
            }
            set
            {
                this.roleIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public System.Nullable<bool> IsPivot
        {
            get
            {
                return this.isPivotField;
            }
            set
            {
                this.isPivotField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = true)]
    public partial class FactRole
    {

        private int declaringTypeIdField;

        private bool isPivotField;

        private int roleIdField;

        private string roleNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DeclaringTypeId
        {
            get
            {
                return this.declaringTypeIdField;
            }
            set
            {
                this.declaringTypeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsPivot
        {
            get
            {
                return this.isPivotField;
            }
            set
            {
                this.isPivotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RoleId
        {
            get
            {
                return this.roleIdField;
            }
            set
            {
                this.roleIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string RoleName
        {
            get
            {
                return this.roleNameField;
            }
            set
            {
                this.roleNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = true)]
    public partial class FactType
    {

        private int typeIdField;

        private string typeNameField;

        private int versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TypeId
        {
            get
            {
                return this.typeIdField;
            }
            set
            {
                this.typeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string TypeName
        {
            get
            {
                return this.typeNameField;
            }
            set
            {
                this.typeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = true)]
    public partial class ArrayOfFact
    {

        private Fact[] factField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fact", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public Fact[] Fact
        {
            get
            {
                return this.factField;
            }
            set
            {
                this.factField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = true)]
    public partial class ArrayOfPredecessor
    {

        private Predecessor[] predecessorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Predecessor", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public Predecessor[] Predecessor
        {
            get
            {
                return this.predecessorField;
            }
            set
            {
                this.predecessorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = true)]
    public partial class ArrayOfFactRole
    {

        private FactRole[] factRoleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FactRole", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public FactRole[] FactRole
        {
            get
            {
                return this.factRoleField;
            }
            set
            {
                this.factRoleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = true)]
    public partial class ArrayOfFactType
    {

        private FactType[] factTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FactType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public FactType[] FactType
        {
            get
            {
                return this.factTypeField;
            }
            set
            {
                this.factTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = false)]
    public partial class GetRequest
    {

        private string domainField;

        private FactTree pivotTreeField;

        private long pivotIdField;

        private long timestampField;

        private string clientGuidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string Domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public FactTree PivotTree
        {
            get
            {
                return this.pivotTreeField;
            }
            set
            {
                this.pivotTreeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PivotId
        {
            get
            {
                return this.pivotIdField;
            }
            set
            {
                this.pivotIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientGuid
        {
            get
            {
                return this.clientGuidField;
            }
            set
            {
                this.clientGuidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = false)]
    public partial class GetResponse
    {

        private FactTree factTreeField;

        private long timestampField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public FactTree FactTree
        {
            get
            {
                return this.factTreeField;
            }
            set
            {
                this.factTreeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = false)]
    public partial class GetManyRequest
    {

        private string domainField;

        private FactTree pivotTreeField;

        private ArrayOfPivotIdPivotId[] pivotIdsField;

        private string clientGuidField;

        private int timeoutSecondsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string Domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public FactTree PivotTree
        {
            get
            {
                return this.pivotTreeField;
            }
            set
            {
                this.pivotTreeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PivotId", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ArrayOfPivotIdPivotId[] PivotIds
        {
            get
            {
                return this.pivotIdsField;
            }
            set
            {
                this.pivotIdsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientGuid
        {
            get
            {
                return this.clientGuidField;
            }
            set
            {
                this.clientGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TimeoutSeconds
        {
            get
            {
                return this.timeoutSecondsField;
            }
            set
            {
                this.timeoutSecondsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    public partial class ArrayOfPivotIdPivotId
    {

        private System.Nullable<long> factIdField;

        private long timestampField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public System.Nullable<long> FactId
        {
            get
            {
                return this.factIdField;
            }
            set
            {
                this.factIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = false)]
    public partial class GetManyResponse
    {

        private FactTree factTreeField;

        private ArrayOfPivotIdPivotId[] pivotIdsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public FactTree FactTree
        {
            get
            {
                return this.factTreeField;
            }
            set
            {
                this.factTreeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PivotId", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ArrayOfPivotIdPivotId[] PivotIds
        {
            get
            {
                return this.pivotIdsField;
            }
            set
            {
                this.pivotIdsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = false)]
    public partial class PostRequest
    {

        private string domainField;

        private FactTree messageBodyField;

        private string clientGuidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string Domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public FactTree MessageBody
        {
            get
            {
                return this.messageBodyField;
            }
            set
            {
                this.messageBodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientGuid
        {
            get
            {
                return this.clientGuidField;
            }
            set
            {
                this.clientGuidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = false)]
    public partial class PostResponse
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = false)]
    public partial class SubscribeRequest
    {

        private string domainField;

        private FactTree pivotTreeField;

        private long pivotIdField;

        private string deviceUriField;

        private string clientGuidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string Domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public FactTree PivotTree
        {
            get
            {
                return this.pivotTreeField;
            }
            set
            {
                this.pivotTreeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PivotId
        {
            get
            {
                return this.pivotIdField;
            }
            set
            {
                this.pivotIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string DeviceUri
        {
            get
            {
                return this.deviceUriField;
            }
            set
            {
                this.deviceUriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientGuid
        {
            get
            {
                return this.clientGuidField;
            }
            set
            {
                this.clientGuidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = false)]
    public partial class UnsubscribeRequest
    {

        private string domainField;

        private FactTree pivotTreeField;

        private long pivotIdField;

        private string deviceUriField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string Domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public FactTree PivotTree
        {
            get
            {
                return this.pivotTreeField;
            }
            set
            {
                this.pivotTreeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PivotId
        {
            get
            {
                return this.pivotIdField;
            }
            set
            {
                this.pivotIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string DeviceUri
        {
            get
            {
                return this.deviceUriField;
            }
            set
            {
                this.deviceUriField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = false)]
    public partial class SubscribeResponse
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://correspondence.updatecontrols.com/pox/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://correspondence.updatecontrols.com/pox/1.0", IsNullable = false)]
    public partial class UnsubscribeResponse
    {
    }
}
