//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateControls.Correspondence.Factual.UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateControls.Correspondence.Factual.UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace SharedProjects.Model;
        ///strength us_1_1;
        ///
        ///fact Token {
        ///key:
        ///	string identifier;
        ///}
        ///
        ///fact Project {
        ///key:
        ///	unique;
        ///	lock;
        ///}
        ///
        ///fact Individual {
        ///key:
        ///	unique;
        ///	principal;
        ///
        ///query:
        ///	Accept* projectsAccepted {
        ///		Accept a : a.grant.request.individual = this
        ///			where not a.isDeleted
        ///	}
        ///}
        ///
        ///fact Request {
        ///key:
        ///	publish Individual individual;
        ///	publish Token token;
        ///
        ///	from individual;
        ///}
        ///
        ///fact Grant {
        ///key:
        ///	Request request;
        ///	Project project;
        ///
        ///	to request.individual;
        ///	unlock p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AsymmetricSecurityModel {
            get {
                return ResourceManager.GetString("AsymmetricSecurityModel", resourceCulture);
            }
        }
    }
}
